# Generated by Django 3.2.9 on 2021-12-27 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='annoncementfile')),
                ('title', models.CharField(max_length=80)),
                ('desc', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=80)),
            ],
        ),
    ]
