# Generated by Django 3.2.9 on 2021-12-27 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll_Data',
            fields=[
                ('sheet_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('enroll_datasheet', models.FileField(upload_to='enroll_datasheets')),
            ],
        ),
    ]
