# Generated by Django 3.2.9 on 2021-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_enroll_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('branch', models.CharField(choices=[('BTECH', 'BTECH'), ('MTECH', 'MTECH')], max_length=100)),
                ('course', models.CharField(choices=[('BTECH', 'BTECH'), ('MTECH', 'MTECH')], max_length=100)),
                ('Reg_no', models.CharField(max_length=10, unique=True)),
                ('roll_no', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('session', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
