# Generated by Django 3.2.9 on 2021-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_registeredstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredstudents',
            name='branch',
            field=models.CharField(choices=[('CIVIENG', 'CIVIENG'), ('COMPENG', 'COMPENG'), ('ECIENG', 'ECIENG'), ('ECTELEG', 'ECTELEG'), ('ITENG', 'ITENG'), ('MECHENG', 'MECHENG')], max_length=100),
        ),
    ]
