# Generated by Django 3.2.9 on 2021-12-27 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_registeredstudents_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('enroll_datasheet', models.ImageField(upload_to='FrontImage')),
            ],
        ),
    ]
