# Generated by Django 3.2.9 on 2021-12-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_frontimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontimage',
            old_name='enroll_datasheet',
            new_name='image',
        ),
    ]
