# Generated by Django 3.2.9 on 2021-12-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontimage',
            name='title',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
